development:
  database: rails_base_app_development
  adapter:  mysql2
  encoding: utf8
  pool:     5
  username: #USERNAME#
  password: #PASSWORD#
  host:    localhost

test:
  database: rails_base_app_test
  adapter:  mysql2
  encoding: utf8
  pool:     5
  username: #USERNAME#
  password: #PASSWORD#
  host:    localhost

production:
  host: <%= ENV["DATABASE_HOST"] %>
